### ISSUE TITLE
TauDEM on Qgis 3.4 - The following layers were not correctly generated.<ul><li>

### ISSUE THREAD

**Issue by vzthiago** [alexbruy/processing-taudem#10]
Hi. I'm having an issue running TauDEM on Qgis 3.4. I'm able to run the program on the command line but not on Qgis. It gives me this error. 
I followed some suggestions online but so far I couldn't make it work.

any suggestions? 
Thank you,

```
Processing algorithm…
Algorithm 'Pit remove' starting…
Input parameters:
{ 'DEPRESSION_MASK' : None, 'ELEVATION' : 'C:/taudem/Logan/logan.tif', 'FOUR_NEIGHBOURS' : False, 'PIT_FILLED' : 'C:/Users/thiag/AppData/Local/Temp/processing_00f52116130a403e80929fbbe521f466/fb83cb20383443f99c644171afb0642d/PIT_FILLED.tif' }

TauDEM command:
"C:\Program Files\MicrosoftMPI\bin\mpiexec" -n 12 "C:\Program Files\TauDEM\TauDEM5Exe\pitremove" -z C:/taudem/Logan/logan.tif -fel C:/Users/thiag/AppData/Local/Temp/processing_00f52116130a403e80929fbbe521f466/fb83cb20383443f99c644171afb0642d/PIT_FILLED.tif
TauDEM command output:
Execution completed in 0.23 seconds
Results:
{'PIT_FILLED': <QgsProcessingOutputLayerDefinition {'sink':C:/Users/thiag/AppData/Local/Temp/processing_00f52116130a403e80929fbbe521f466/fb83cb20383443f99c644171afb0642d/PIT_FILLED.tif, 'createOptions': {'fileEncoding': 'System'}}>}

Loading resulting layers
**The following layers were not correctly generated.<ul><li>C:/Users/thiag/AppData/Local/Temp/processing_00f52116130a403e80929fbbe521f466/fb83cb20383443f99c644171afb0642d/PIT_FILLED.tif</li></ul>You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.**
```

**Comment by alexbruy** [comment]
First of all, don't follow these absolutely incorrect suggestions. There is a **standard** way to install plugins in QGIS.

Secondly, please, provide information about your environment and plugin version in the bugreport. 

Not reproducible on latest 3.4 nightly, TauDEM provider 3.0 and TauDEM 5.3.7. Also not reproducible on master with same plugin and TauDEM versions.

**Comment by vzthiago** [comment]
Hi Alex. Thank you for your reply and attention. Sorry if I was not clear before. I'm very new to this universe of Qgis. 

I'm using TauDEM 5.3.7 / Qgis 3.4.11. / and your code is the branch release-3_0. I did not create a env for it. Just installed and add to the processing toolbar with the paths for mpi and taudem.exe. 

Is that the information you are looking for? But, from your previous reply, I think is because I'm using TauDEM 5.3.7, correct? should I try the 5.3.5 then?

**Comment by alexbruy** [comment]
Please read my previous reply carefully.

> Not reproducible on latest 3.4 nightly, TauDEM provider 3.0 and TauDEM 5.3.7. Also not reproducible on master with same plugin and TauDEM versions.

Looks like this is local issue, probably caused by incorrect plugin installation.

**Comment by vzthiago** [comment]
Ok Alex. Thank you for pointing out. Any suggestions on what is the best package to use then? Like, should I try Qgis 3.8 and TauDEM 5.3.5? Thank you in advance.
