### ISSUE TITLE
NameError when trying a function

### ISSUE THREAD

**Issue by untoldstory2** [alexbruy/processing-taudem#12]
When I try any function in TauDEM I get the error:
```
Traceback (most recent call last):
File "C:/Users/gcooper/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_taudem\taudemAlgorithm.py", line 54, in processAlgorithm
command = generateCommand(self, parameters, context, feedback)
NameError: name 'generateCommand' is not defined

Execution failed after 0.12 seconds
```

**Comment by alexbruy** [comment]
Not reproducible with the latest published plugin from repository.

**Comment by david-laverty** [comment]
I am having same issue as OP when upgrading plugin from experimental version 2.1 (working on my machine) to version 3.0 master from your repository. I am running QGIS 3.10.2 on windows 10.
Plugin was installed via zip file downloaded from master
