### ISSUE TITLE
error: NameError: name 'generateCommand' is not defined

### ISSUE THREAD

**Issue by yhan27** [alexbruy/processing-taudem#14]
Note: This issue has been brought up by others, but since the author closed them out, I decided to start a new issue thread here.

Hi, I ended up with the following error message after I successfully installed the plug in and TauDEM executive files. thought? Error Message below after I tried to run pit remove function from QGIS 3.8.3, 64bit, windows 10.
```
Traceback (most recent call last):
File "C:/Users/myname/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_taudem\taudemAlgorithm.py", line 54, in processAlgorithm
command = generateCommand(self, parameters, context, feedback)
NameError: name 'generateCommand' is not defined

Execution failed after 0.04 seconds
```

**Comment by alexbruy** [comment]
Duplicates #12 and #13. Please read these tickets and don't post duplicates, there is no issue in the latest published version.

**Comment by yhan27** [comment]
I am not sure why you said that, but the fact is I installed the newest version and ended up with the error message. and there are other people having  the same issue (#12 and #13). I read the tickets but it seems there is no solutions provided. Thank you.
