### ISSUE TITLE
NameError: name 'generateCommand' is not defined

### ISSUE THREAD

**Issue by JayMatsushiba** [alexbruy/processing-taudem#15]
Hello, I am attempting to use your tool and TauDEM in QGIS and am facing this error. I noticed that there are 3 other issues that you have marked as resolved, but it seems like no solution has been outlined. Please advise on this issue. Thank you. 

Traceback (most recent call last):
File "C:/Users/Jay Workstation/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_taudem\taudemAlgorithm.py", line 56, in processAlgorithm
NameError: name 'generateCommand' is not defined

**Comment by alexbruy** [comment]
Duplicates #12, #13 and #14. Please read these tickets and don't post duplicates, there is no issue in the latest published version.
