### ISSUE TITLE
QGIS3

### ISSUE THREAD

**Issue by NicolasCadieux** [alexbruy/processing-taudem#16]
Hi,
This page https://plugins.bruy.me/plugins/plugins.xml indicates the minimum version of QGIS is 3.0 but in QGIS3.16, It indicates the plugin is for <2.99.
Is there a QGIS3 version?
Thanks!

**Comment by alexbruy** [comment]
Apparently, you are doing something really wrong. Version from the repository works fine in the latest master.

**Comment by NicolasCadieux** [comment]
> Apparently, you are doing something really wrong. Version from the repository works fine in the latest master.

Hi,
I basically downloaded the GitHub master and unzipped the entire file structure in the plugin folder. I will retest.
Nicolas

**Comment by alexbruy** [comment]
GitHub is for developers and power users. For average users there is a repository.
