### ISSUE TITLE
TauDem Plugin instllation error message

### ISSUE THREAD

**Issue by yhan27** [alexbruy/processing-taudem#17]
When installing TauDem, an error message pops up: Plugin installation failed: Error transferring https://plugins.bruy.me/plugins/processing_taudem.zip - server replied: Not Found. This is new. Please investigate. Thanks.

**Comment by CorentinBoyeau** [comment]
Same problem here, have you found a solution?

**Comment by yhan27** [comment]
no. waiting for the author to respond.
