### ISSUE TITLE
Peuker Douglas Stream Definition function missing

### ISSUE THREAD

**Issue by ArrEssJay** [alexbruy/processing-taudem#9]
The Peuker Douglas Stream Definition referred to in the TauDEM documentation appears to be missing in the QGIS integration:

http://hydrology.usu.edu/taudem/taudem5/help53/PeukerDouglasStreamDefinition.html

Fortunately, looking at the arcpy code, it is implemented as a concatenation of other operations in the front end integration, so I think it would be trivial to add.

Arcpy integration:
https://github.com/dtarb/TauDEM/blob/Develop/pyfiles/PeukerDouglasStreamDef.py

**Comment by alexbruy** [comment]
Closing as invalid.
